### ISSUE TITLE
Pact.publish() fails when passing argument to pact_dir parameter

### ISSUE THREAD

**Issue by lucaromagnoli** [pact-foundation/pact-python#128]
As per title,

When I try to publish automatically to the broker while passing a custom folder argument to `pact_dir`, the pact fails to be published.

Example:
```
pact = (
    Consumer('myservice-service', version='1.0.0')
    .has_pact_with(
        Provider('provider-service'),
        log_dir=LOGS_DIR,
        pact_dir=PACTS_DIR,
        broker_base_url='https://xxx.pact.dius.com.au/',
        publish_to_broker=True,
        broker_username=os.environ.get('BROKER_USERNAME'),
        broker_password=os.environ.get('BROKER_PASSWORD')
    )
)
pact.start_service()
atexit.register(pact.stop_service)

def test():
    ....
```

The same test works as expected when I don't provide a custom pact folder.
I'm using `pact-python==0.21.0`.

Below is the full stack trace (had to hide some information about filename and publisher URL)
```
/Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/pact_file.rb:32:in `read': No such file or directory @ rb_sysopen - xxx.json (Errno::ENOENT)
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/pact_file.rb:32:in `read'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/pact_file.rb:28:in `pact_hash'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/pact_file.rb:16:in `pact_name'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_list.rb:81:in `each'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_list.rb:81:in `group_by'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_list.rb:81:in `group_by'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/publish_pacts.rb:41:in `publish_pacts'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/publish_pacts.rb:27:in `call'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/publish_pacts.rb:13:in `call'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/cli/broker.rb:159:in `publish_pacts'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/cli/broker.rb:59:in `publish'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.24.0/lib/pact_broker/client/cli/custom_thor.rb:15:in `start'
        from /Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/bin/pact/lib/app/pact-broker.rb:28:in `<main>'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/pact.py", line 261, in stop_service
    self.publish()
  File "/Users/luca.romagnoli/.local/share/virtualenvs/xxx-89oxPR3E/lib/python3.7/site-packages/pact/pact.py", line 194, in publish
    .format(url))
RuntimeError: There was an error while publishing to the pact broker at https://xxx.pact.dius.com.au/.
```

EDIT.
Upon further investigation it appears that using a relative path seems to work. It still fails when providing an absolute path

**Comment by niciqy** [comment]
How are you publishing your pacts? Are you using `pact_broker-client`? If so, are you setting the directory correctly? 
```
pact-broker publish PACT_DIRS_OR_FILES ... -a, --consumer-app-version=CONSUMER_APP_VERSION -b, --broker-base-url=BROKER_BASE_URL```

**Comment by elliottmurray** [comment]
I think this is the publish function - it lists the directories contents in PACT_DIR but isn't preserved when it's passed to the ruby process. I'll get around to this at some point but a few workarounds.

**Comment by QA-HH** [comment]
@lucaromagnoli I have the same problem, but could not make it work also with a relative path. Can you share a version of the code which worked for you? Thanks

**Comment by bethesque** [comment]
The CLI thinks that the pact dir is relative to where the process is being executed from, so if the CLI is being called from the base directory of the project, then it should correctly resolve relative paths from with the project. Perhaps the CLI is being called from its own directory?

**Comment by cdambo** [comment]
@bethesque - it seems that no matter what I pass in to pact-python as the `pact_dir`, it then passes to the ruby CLI just the filenames in that directory (as seen [here](https://github.com/pact-foundation/pact-python/blob/v1.2.11/pact/pact.py#L164-L167)).

If we change those lines to re-add the `pact_dir` to the result of the filter, like this:

```python
pact_files = map(
    lambda filename: os.path.join(self.pact_dir, filename), 
    fnmatch.filter(
        os.listdir(self.pact_dir),
        self._normalize_consumer_name(self.consumer.name) + '*.json'
    )
)
```

It will send to the CLI the file paths including the `pact_dir`, and will prevent this error.

**Comment by sergii-tsymbal-exa** [comment]
Experienced this error in 1.3.5
It fails also when using a relative path
This PR seems to fix the issue: https://github.com/pact-foundation/pact-python/pull/195. But for some reason, it has been merged to `pact-foundation:master` instead of `master`
@elliottmurray, what's preventing us from fixing this in master? Let me know if some help is needed here
