### ISSUE TITLE
 pact-verifier fails with SSL error when using a secure pact broker

### ISSUE THREAD

**Issue by amrithajayadev** [pact-foundation/pact-python#143]
I have pact-python-1.0.1 installed. My pact broker runs on 8443 and uses https scheme. I see that the latest version of pact-provider-verifier ruby 1.30.1 has SSL verification disabled, and my pact-python seems to be using the same version,but I can't get it working. 

How I ran the verification:
```
pact-verifier --provider-base-url=http://localhost:9099 --provider-states-url=http://localhost:9099/pact/provider_states/all --provider-states-setup-url=http://localhost:9099/pact
/provider_states --pact-broker-url https://my.pact.broker.com:8443 --provider python-producer --provider-app-version 1.0.0 --publish-verification-results
```
Logs:
```
Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed , attempt 1 of 3
Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed , attempt 2 of 3
Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed , attempt 3 of 3
C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/ruby/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
 (OpenSSL::SSL::SSLError)
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/ruby/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/ruby/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/ruby/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/ruby/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/ruby/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/hal/http_client.rb:55:in `block in perform_request'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/retry.rb:23:in `until_true'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/hal/http_client.rb:49:in `perform_request'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/hal/http_client.rb:24:in `get'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/hal/link.rb:49:in `get'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/pact_broker/fetch_pact_uris_for_verification.rb:50:in `index'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/pact_broker/fetch_pact_uris_for_verification.rb:37:in `call'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/pact_broker/fetch_pact_uris_for_verification.rb:33:in `call'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/pact_broker.rb:18:in `fetch_pact_uris_for_verification'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/aggregate_pact_configs.rb:45:in `pacts_for_verificat
ion'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/aggregate_pact_configs.rb:38:in `pacts_urls_from_bro
ker'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/aggregate_pact_configs.rb:25:in `call'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/aggregate_pact_configs.rb:10:in `call'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:197:in `all_pact_urls'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:40:in `call'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:34:in `call'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/cli/verify.rb:56:in `verify'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
        from C:/CloudIQ/python-producer/venv/Lib/site-packages/pact/bin/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

**Comment by bethesque** [comment]
There's a working example using docker compose here https://github.com/DiUS/pact_broker-docker/blob/master/docker-compose.yml

**Comment by elliottmurray** [comment]
I think this is resolved

**Comment by bethesque** [comment]
For future reference, docs here for accessing a broker over https https://docs.pact.io/pact_broker/advanced_topics/using-tls/#connecting-to-a-pact-broker-running-over-tls
