### ISSUE TITLE
Pact-Verifier : ValueError: 'default' must be a list when 'multiple' is true.

### ISSUE THREAD

**Issue by ssshauryaa** [pact-foundation/pact-python#261]
Running Pact-Verifier commands throws this error. pact-python version is 1.3.1.

root# pact-verifier --help

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.3/bin/pact-verifier", line 33, in <module>
    sys.exit(load_entry_point('pact-python==1.3.1', 'console_scripts', 'pact-verifier')())
  File "/root/.pyenv/versions/3.6.3/bin/pact-verifier", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pact/cli/verify.py", line 122, in <module>
    help='Automatically include the pending pacts in the verification step. '
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/click/core.py", line 2110, in __init__
    ) from None
ValueError: 'default' must be a list when 'multiple' is true.

**Comment by elliottmurray** [comment]
Is this still an issue in latest (1.4.3)?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
