### ISSUE TITLE
Provide a way to hide ruby traceback on provider verification failure

### ISSUE THREAD

**Issue by dhoomakethu** [pact-foundation/pact-python#59]
At present the failure of provider verification tests results in massive ruby traceback which is not really required for the end user. Please provide an option to hide this traceback.

Ex.
```
Failure/Error: expect(response_body).to match_term expected_response_body, diff_options

     RuntimeError:
       Sorry, "\d+" is too vague, try setting a range: "\d{1, 5}"
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:82:in `digit'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:19:in `random'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:4:in `reduce'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:12:in `quantify'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:4:in `reduce'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:53:in `block in union'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:53:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:53:in `union'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/reducer.rb:4:in `reduce'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp.rb:9:in `reduce'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/randexp-0.1.7/lib/randexp/core_ext/regexp.rb:3:in `generate'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/reification.rb:17:in `from_term'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/reification.rb:20:in `block in from_term'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/reification.rb:19:in `each'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/reification.rb:19:in `inject'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/reification.rb:19:in `from_term'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/matchers/matchers.rb:126:in `hash_diff'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/matchers/matchers.rb:43:in `calculate_diff'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/matchers/matchers.rb:31:in `diff'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.3/lib/pact/shared/json_differ.rb:10:in `call'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/rspec/matchers.rb:36:in `matches?'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/rspec.rb:138:in `block (2 levels) in describe_response'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:254:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:589:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1894:in `with_suite_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:79:in `report'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:94:in `run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:35:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:22:in `call'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:66:in `block in verify_pacts'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:57:in `collect'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:57:in `verify_pacts'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/cli.rb:21:in `verify'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/app/pact-provider-verifier.rb:2:in `<main>'
```

```
Failure/Error: expect(header_value).to match_header(name, expected_header_value)
       Expected header "Content-Type" to match "application/json", but was "text/plain; charset=utf-8"
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:87:in `block in <module:Support>'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:96:in `call'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:96:in `notify_failure'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/rspec.rb:130:in `block (4 levels) in describe_response'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:254:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:589:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `map'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1894:in `with_suite_hooks'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:79:in `report'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:94:in `run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:35:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:22:in `call'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:66:in `block in verify_pacts'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:57:in `collect'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:57:in `verify_pacts'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/cli.rb:21:in `verify'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
     # /usr/local/lib/python3.5/site-packages/pact/bin/pact/lib/app/pact-provider-verifier.rb:2:in `<main>'

3 interactions, 1 failure

Failed interactions:

bundle exec rake pact:verify:at[pacts/auth-userservice.json] PACT_DESCRIPTION="a request is made to validate user" PACT_PROVIDER_STATE=""
```

**Comment by bethesque** [comment]
This error is actually a bug in the ruby implementation, and has already been fixed. Please update to the latest standalone executable @matthewbalvanz-wf. The stacktrace should never be shown like this under normal operation.

**Comment by bethesque** [comment]
Ugh, ok, that second one is normal usage actually. I've raised it here: https://github.com/realestate-com-au/pact/issues/146

**Comment by richard-reece** [comment]
I just stripped out any line in the response that starts with '#' :-)
`    def verify_pact(self, provider_url, pact_url, states_setup_url=None):
        # launch ruby verifier
        command = [
            VERIFIER_PATH,
            '--provider-base-url', provider_url,
            '--pact-urls', pact_url,
        ]
        if states_setup_url:
            command.extend(['--provider-states-setup-url', states_setup_url])
        p = subprocess.run(command, stdout=subprocess.PIPE, universal_newlines=True)

        # strip out ruby traceback
        lines = p.stdout.splitlines()
        print('\n'.join(line for line in lines if not line.lstrip().startswith('#')))

        # return success
        return p.returncode == 0
`

**Comment by bethesque** [comment]
Just to be on the safe side, perhaps remove lines that start with a # and also have "vendor/ruby" in them.
