### ISSUE TITLE
"There was an error when stopping the Pact mock service"

### ISSUE THREAD

**Issue by jaredhm** [pact-foundation/pact-python#66]
---------------------------------
### System Info
```
⇒  uname -a
Linux dev 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
---------------------------------
### Versions
```
⇒  python3 --version
Python 3.5.2
⇒  pip3 --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
```

version of `pact-python` is 0.10.0

----------------------------------
### Recreating the Issue
So you can recreate using just the example consumer test included in the README. Here, I've modified it slightly.

From `consumer_contract.py`:
```
import atexit
import unittest
import requests

from pact import Consumer, Provider

pact = Consumer('Consumer').has_pact_with(Provider('Provider'))
pact.start_service()
atexit.register(pact.stop_service)

class GetUserInfoContract(unittest.TestCase):
  def test_get_user(self):
    expected = {
      'username': 'UserA',
      'id': 123,
      'groups': ['Editors']
    }

    (pact
     .given('UserA exists and is not an administrator')
     .upon_receiving('a request for UserA')
     .with_request('get', '/users/UserA')
     .will_respond_with(200, body=expected))

    with pact:
      r = requests.get('http://localhost:1234/users/UserA')

    self.assertEqual(r.json()['username'], 'UserA')

if __name__ == '__main__':
    unittest.main()
```
---------------------------
### The Problem
If I now do a `python3 consumer_contract.py`, I get the following stack traces:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f8379434518>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    pact.start_service()
  File "/usr/local/lib/python3.5/dist-packages/pact/pact.py", line 152, in start_service
    self._wait_for_server_start()
  File "/usr/local/lib/python3.5/dist-packages/pact/pact.py", line 256, in _wait_for_server_start
    resp = s.get(self.uri, headers=self.HEADERS)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```
WEBrick then goes on to start up asynchronously and run in the background. If I then attempt to generate the contract file again, I get the following:
```
.
----------------------------------------------------------------------
Ran 1 test in 0.057s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pact/pact.py", line 168, in stop_service
    'There was an error when stopping the Pact mock service.')
RuntimeError: There was an error when stopping the Pact mock service.
```

...because the mock server is still running. Only once I manually `kill` ruby does the contract get written. What am I doing wrong? It seems like my use case is pretty simple here.

**Comment by jaredhm** [comment]
Ok so update: I fiddled with `pact.py` and had `_wait_for_server_start` pass the max number of retries in as an integer rather than as a `Retry` object.

I tried to run the contracts again and got 
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa63daf8d68>: Failed to establish a new connection: [Errno 111] Connection refused',))

requests.packages.urllib3.util.retry: DEBUG: Converted retries value: 15 -> Retry(total=15, connect=None, read=None, redirect=None)
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=14, connect=None, read=None, redirect=None)
requests.packages.urllib3.connectionpool: WARNING: Retrying (Retry(total=14, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa63df3d780>: Failed to establish a new connection: [Errno 111] Connection refused',)': /
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (2): localhost
requests.packages.urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=13, connect=None, read=None, redirect=None)
requests.packages.urllib3.connectionpool: WARNING: Retrying (Retry(total=13, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa63df617b8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (3): localhost
requests.packages.urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=12, connect=None, read=None, redirect=None)
requests.packages.urllib3.connectionpool: WARNING: Retrying (Retry(total=12, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa63df61940>: Failed to establish a new connection: [Errno 111] Connection refused',)': /
....
```

**Comment by jaredhm** [comment]
(Another) update: a coworker tried to replicate and couldn't. So, I'll close this issue and try to figure out what's gone wrong on my end.
